kafka:
  properties:
    bootstrap.servers: kafka.host:9092 # TODO
    security.protocol: SASL_PLAINTEXT # TODO
    sasl.mechanism: SCRAM-SHA-512 # TODO
    sasl.username: test-username # TODO
    sasl.password: '' # TODO
