{{- define "generic-chart.container_spec.tpl" -}}
{{- $ctx := . -}}
{{- $container := dict -}}
{{- if and (kindIs "map" .) (hasKey . "ctx") -}}
  {{- $ctx = .ctx -}}
  {{- $container = .container | default dict -}}
{{- end -}}
name: {{ default (include "generic-chart.containerName" $ctx) $container.name }}
{{- $containerSecurityContext := $ctx.Values.containerSecurityContext }}
{{- if hasKey $container "containerSecurityContext" }}
  {{- $containerSecurityContext = $container.containerSecurityContext }}
{{- end }}
{{- with $containerSecurityContext }}
securityContext:
  {{- toYaml . | nindent 2 }}
{{- end }}{{- /* securityContext */}}
{{- end }} {{- /* define */}}
