{{- define "generic-chart.httpRoute.tpl" -}}
{{- if (.Values.httpRoute).enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "generic-chart.fullname" . }}
spec:
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  parentRefs:
    {{- include "generic-chart.httpRouteParentRefs" . | nindent 4 }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{  include "generic-chart.fullname" . }}
          port: {{ (.Values.service).port | default 80 | int }}
          weight: 1
{{- end }}{{/* if enabled */}}
{{- end }}{{/* define */}}
