{{/*
Renders a PodDisruptionBudget resource.

This helper can be reused for multiple objects within a single chart.

Behavior:
- Uses `.pdbctx` if provided
- Falls back to `.Values.pdb` otherwise

Usage:

1. Single object with default chart values:
   {{- template "generic-chart.pdb.tpl" . }}

2. Object with custom PDB values:
   {{- define "mynewshiny.pdb" }}
   metadata:
     name: {{ include "generic-chart.fullname" . }}-newshiny
   {{- end }}

   {{- template "generic-chart.merge" (list
       (merge (dict "pdbctx" .Values.my.new.shiny.pdb) .)
       "mynewshiny.pdb"
       "generic-chart.pdb.tpl"
   ) }}

*/}}
{{- define "generic-chart.pdb.tpl" -}}
{{- $ctx := . }}
{{- $pdbctx := .pdbctx | default .Values.pdb }}
{{- with $pdbctx }}
{{- if .enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "generic-chart.fullname" $ctx }}
  labels:
    {{- include "generic-chart.labels" $ctx | nindent 4 }}
spec:
  {{- if .minAvailable }}
  minAvailable: {{ .minAvailable }}
  {{- end }}
  {{- if .maxUnavailable }}
  maxUnavailable: {{ .maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic-chart.selectorLabels" $ctx | nindent 6 }}
      {{- if .component }}
      app.kubernetes.io/component: {{ .component }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }} {{- /* define */}}
