---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "generic-chart.fullname" . }}-delete-hook
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
  # 24h
  ttlSecondsAfterFinished: 86400
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      labels:
        {{- include "generic-chart.labels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- include "tplvalues.render" ( dict "value" .Values.affinity "context" . ) | nindent 8 }}
      {{- end }}{{- /* affinity */}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccount: {{ include "navi-data-sync.deleteHookServiceAccountName" . }}
      # failures managed by Job, not Pod
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-delete-hook
          image: "{{ required "A valid .Values.dgctlDockerRegistry entry required" .Values.dgctlDockerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - "/usr/local/bin/navi-data-sync"
            - "--no-dry-run"
            - "--action=uninstall"
            - "--type={{ .Values.type }}"
            - "--data-group-prefix={{ .Values.dataGroup.prefix }}"
            - "--navi-group={{ .Values.navigroup }}"
            - "--chart-values-back=./resources/navi-back.values.yaml"
            - "--chart-values-attr=./resources/navi-attractor.values.yaml"
            - "--chart-file-back=./resources/navi-back.tgz"
            - "--chart-file-attr=./resources/navi-attractor.tgz"
            - "--chart-name-back={{ .Values.naviBack.releaseName }}"
            - "--chart-name-attr={{ .Values.naviAttractor.releaseName }}"
            - "--castle-url={{ .Values.castleUrl }}"
            - '--chart-fullname-self={{ include "navi-data-sync.cronjobName" . }}'
            - "--helm-timeout={{ .Values.helmTimeout }}"
            {{- if .Values.metrics.enabled }}
            - "--metrics-gateway-url={{ .Values.metrics.gateway }}"
            {{- range $labelName, $labelValue := .Values.metrics.labels }}
            - "--metrics-labels"
            - {{ printf "%s=%s" $labelName $labelValue | quote }}
            {{- end }}{{- /* range */}}
            {{- end }}{{- /* if */}}
            {{- with .Values.projects }}
            - "--projects"
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.routing }}
            - "--routing"
            {{- toYaml . | nindent 12 }}
            {{- end }}
          workingDir: /opt/2gis
          env:
            - name: HELM_MAX_HISTORY
              value: "{{ .Values.helmMaxHistory | default 10 | int }}"
