---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-chart.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
immutable: true
type: Opaque
data:
  {{- if .Values.naviAttractor.templateContentBase64 }}
  navi-attractor.tgz: |
    {{ .Values.naviAttractor.templateContentBase64 | indent 4 }}
  {{- else }}
  navi-attractor.tgz: |
    {{ .Files.Get .Values.naviAttractor.templateFilename | b64enc | indent 4 }}
  {{- end }}
  {{- if .Values.naviBack.templateContentBase64 }}
  navi-back.tgz: |
    {{ .Values.naviBack.templateContentBase64 | indent 4 }}
  {{- else }}
  navi-back.tgz: |
    {{ .Files.Get .Values.naviBack.templateFilename | b64enc | indent 4 }}
  {{- end }}
  navi-attractor.values.yaml: |
    {{ include "navi-data-sync.mergedChildValues" .Values.naviAttractor |
       b64enc |
       indent 4 }}
  navi-back.values.yaml: |
    {{ include "navi-data-sync.mergedChildValues" .Values.naviBack |
       b64enc |
       indent 4 }}
