cassandra:
  credentials:
    user: cassandra
    jmxUser: cassandra
    password: cassandra
    jmxPassword: cassandra
proxy:
  access:
    enabled: true
    syncPeriod: 2m
    vector:
      # predefined.service: tiles-api
      token: 4df2b7c6-9635-4555-9709-3342d17fdf7a
    raster:
      # predefined.service: tiles-raster-api
      token: 1336f9e5-2de5-4a97-b3ff-eb9431eb5da9
