cassandra:
  credentials:
    user: cassandra
    jmxUser: cassandra
    password: '' # TODO
    jmxPassword: '' # TODO
proxy:
  access:
    enabled: true
    syncPeriod: 2m
    vector:
      # сервисный токен tiles-api
      token: '' # TODO
    raster:
      # сервисный токен tiles-raster-api
      token: '' # TODO
