cassandra:
  credentials:
    password: '' # TODO
    jmxPassword: '' # TODO
proxy:
  access:
    vector:
      # сервисный токен tiles-api
      token: '' # TODO
    raster:
      # сервисный токен tiles-raster-api
      token: '' # TODO
