---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "update-manager.name" . }}
  labels:
    {{- include "update-manager.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ required "Valid .Values.postgres.password required!" .Values.postgres.password | b64enc }}
  DATAGATEWAY_API_KEY: {{ required "Valid .Values.api.dgctl.apiKey required!" .Values.api.dgctl.apiKey | b64enc }}
  STORAGE_ACCESS_KEY: {{ required "Valid .Values.dgctlStorage.accessKey required!" .Values.dgctlStorage.accessKey | b64enc }}
  STORAGE_SECRET_KEY: {{ required "Valid .Values.dgctlStorage.secretKey required!" .Values.dgctlStorage.secretKey | b64enc }}
