{{- if not .Values.api.serviceAccountOverride }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "update-manager.name" . }}
  labels:
    {{- include "update-manager.labels" . | nindent 4 }}
{{- end }}
