---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "update-manager.name" . }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "update-manager.labels" . | nindent 4 }}
    {{- with .Values.api.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "update-manager.selectorLabels" . | nindent 4 }}
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: api
