---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mapsapi2.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mapsapi2.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      appProtocol: http
  selector:
    {{- include "mapsapi2.selectorLabels" . | nindent 4 }}
