# @section Docker Registry settings

# @param dgctlDockerRegistry Docker Registry endpoint where On-Premise services' images reside. Format: `host:port`.

dgctlDockerRegistry: ''


# @section Common settings

# @param enableServiceLinks Services injection into containers environment [Accessing the Service](https://kubernetes.io/docs/tutorials/services/connect-applications-service/#accessing-the-service)
# @param replicaCount A replica count for the pod.
# @param revisionHistoryLimit Revision history limit (used for [rolling back](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) a deployment).
# @param terminationGracePeriodSeconds Kubernetes [termination grace period](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/)
# @param imagePullSecrets Kubernetes image pull secrets.
# @param nameOverride Base name to use in all the Kubernetes entities deployed by this chart.
# @param fullnameOverride Base fullname to use in all the Kubernetes entities deployed by this chart.
# @param nodeSelector Kubernetes [node selectors](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector).
# @param affinity Kubernetes pod [affinity settings](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity).
# @param tolerations Kubernetes [tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) settings.
# @param podAnnotations Kubernetes [pod annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/).
# @param podLabels Kubernetes [pod labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).
# @param podSecurityContext Kubernetes [pod security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
# @param securityContext Kubernetes [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
# @param labels Custom labels to set to Deployment resource.
# @param annotations Custom annotations to set to Deployment resource.
# @param priorityClassName Kubernetes [Pod Priority](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass) class name.
# @param initContainers Add additional init containers.
# @param sidecars Add additional sidecar containers.

enableServiceLinks: true
replicaCount: 1
revisionHistoryLimit: 3
terminationGracePeriodSeconds: 30
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
nodeSelector: {}
affinity: {}
tolerations: []
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
labels: {}
annotations: {}
priorityClassName: ''
initContainers: []
sidecars: []


# @section Deployment settings

# @param image.repository Repository
# @param image.tag Tag
# @param image.pullPolicy Pull Policy

image:
  repository: 2gis-on-premise/raster-js-api
  tag: 4.1.0
  pullPolicy: IfNotPresent


# @section API settings

# @param api.publicHost **required** Host on which the service will be available, e.g. 'maps-raster.ingress.host'.
# @param api.protocol Protocol to use: `http:`, `https:`.
# @param api.tileServerUrl URL of the tile server, e.g. 'https://tiles-api.ingress.host'.
# @param api.trafficTileServerUrl URL of the traffic tiles server.
# @param api.trafficTimestampServerUrl URL of the traffic timestamps server.
# @param api.trafficScoreServerUrl URL of the traffic scores server.
# @param api.webApiServerUrl URL of the Catalog API service, e.g. 'https://catalog-api.ingress.host'.
# @param api.webApiKey API key for the Catalog API service. Stored in a Kubernetes Secret and mounted into the container via `secretKeyRef`.
# @param api.key Token from 'keys-api' service. Optional API key that will be included in tile requests. Stored in a Kubernetes Secret and mounted into the container via `secretKeyRef`.
# @param api.keyServerUrl Keys-api service URL

api:
  publicHost: ''
  protocol: 'https:'
  tileServerUrl: ''
  trafficTileServerUrl: ''
  trafficTimestampServerUrl: ''
  trafficScoreServerUrl: ''
  webApiServerUrl: ''
  webApiKey: ''
  key: ''
  keyServerUrl: ''

# @section Strategy settings

# @param strategy.type Type of Kubernetes deployment. Can be `Recreate` or `RollingUpdate`.
# @param strategy.rollingUpdate.maxUnavailable Maximum number of pods that can be created over the desired number of pods when doing [rolling update](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment).
# @param strategy.rollingUpdate.maxSurge Maximum number of pods that can be unavailable during the [rolling update](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment) process.

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1


# @section Service account settings

# @param serviceAccount.create Specifies whether a service account should be created.
# @param serviceAccount.annotations Annotations to add to the service account.
# @param serviceAccount.name The name of the service account to use. If not set and create is true, a name is generated using the fullname template.

serviceAccount:
  create: false
  annotations: {}
  name: ''


# @section Service settings

# @param service.annotations Kubernetes [service annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/).
# @param service.labels Kubernetes [service labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).
# @param service.type Kubernetes [service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
# @param service.port Service port.
# @param service.clusterIP Controls Service cluster IP allocation. Cannot be changed after resource creation.

service:
  annotations: {}
  labels: {}
  type: ClusterIP
  clusterIP: ''
  port: 80


# @section Kubernetes [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) settings

# @param ingress.enabled If Ingress is enabled for the service.
# @param ingress.className Name of the Ingress controller class.
# @param ingress.hosts[0].host Hostname for the Ingress service.
# @param ingress.hosts[0].paths[0].path Path of the host for the Ingress service.
# @param ingress.hosts[0].paths[0].pathType Type of the path for the Ingress service.
# @param ingress.tls TLS configuration

ingress:
  enabled: false
  className: nginx
  hosts:
  - host: raster-js-api.example.com
    paths:
    - path: /
      pathType: Prefix
  tls: []
  # - hosts:
  #   - raster-js-api.example.com
  #   secretName: secret.tls


# @section [HTTPRoute](https://gateway-api.sigs.k8s.io/api-types/httproute/) configuration

# @param httpRoute.enabled If HTTPRoute is enabled for the service.
# @param httpRoute.hostnames List of hostnames served by route.
# @extra httpRoute.parentRefs List of parent references (gateways) for HTTPRoute.

httpRoute:
  enabled: false
  hostnames: []


# @section Limits

# @param resources.requests.cpu A CPU request.
# @param resources.requests.memory A memory request.
# @param resources.limits.cpu A CPU limit.
# @param resources.limits.memory A memory limit.

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 192Mi


# @section Kubernetes [Horizontal Pod Autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) settings

# @param hpa.enabled If HPA is enabled for the service.
# @param hpa.minReplicas Lower limit for the number of replicas to which the autoscaler can scale down.
# @param hpa.maxReplicas Upper limit for the number of replicas to which the autoscaler can scale up.
# @param hpa.scaleDown Scale-down settings structure.
# @param hpa.scaleUp Scale-up settings structure.
# @param hpa.targetCPUUtilizationPercentage Target average CPU utilization (represented as a percentage of requested CPU) over all the pods; if not specified the default autoscaling policy will be used.
# @param hpa.targetMemoryUtilizationPercentage Target average memory utilization (represented as a percentage of requested memory) over all the pods; if not specified the default autoscaling policy will be used.

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  scaleDown: {}
  scaleUp: {}
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: ''


# @section Kubernetes [Vertical Pod Autoscaling](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md) settings

# @param vpa.enabled If VPA is enabled for the service.
# @param vpa.updateMode VPA [update mode](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#quick-start).
# @param vpa.controlledValues Controlled values, one of: RequestsOnly or RequestsAndLimits.
# @extra vpa.minAllowed.cpu Lower limit for the number of CPUs to which the autoscaler can scale down.
# @extra vpa.minAllowed.memory Lower limit for the RAM size to which the autoscaler can scale down.
# @extra vpa.maxAllowed.cpu Upper limit for the number of CPUs to which the autoscaler can scale up.
# @extra vpa.maxAllowed.memory Upper limit for the RAM size to which the autoscaler can scale up.

vpa:
  enabled: false
  updateMode: Auto
  controlledValues: RequestsOnly


# @section Kubernetes [Pod Disruption Budget](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets) settings

# @param pdb.enabled If PDB is enabled for the service.
# @param pdb.minAvailable How many pods must be available after the eviction.
# @param pdb.maxUnavailable How many pods can be unavailable after the eviction.

pdb:
  enabled: false
  minAvailable: ''
  maxUnavailable: 1


# @section customCAs **Custom Certificate Authority**

# @param customCAs.bundle Custom CA [text representation of the X.509 PEM public-key certificate](https://www.rfc-editor.org/rfc/rfc7468#section-5.1)
# @param customCAs.certsPath Custom CA bundle mount directory in the container. If empty, the default value: "/usr/local/share/ca-certificates"

customCAs:
  bundle: ''
# bundle: |
    # -----BEGIN CERTIFICATE-----
    # ...
    # -----END CERTIFICATE-----
  certsPath: ''
