kafka:
  solver:
    sensitiveProperties:
      sasl.plain.password: admin
  dm:
    sensitiveProperties:
      sasl.plain.password: admin
keys:
  # predefined.service: tsp-api
  token: bcd55b3e-c0d1-4374-84f4-b9277674fb46
db:
  password: vrp_password
