kafka:
  solver:
    properties:
      bootstrap.servers: kafka-controller-headless:9092
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-512
      sasl.plain.username: admin
    sensitiveProperties:
      sasl.plain.password: admin
  dm:
    properties:
      bootstrap.servers: kafka-controller-headless:9092
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-512
      sasl.plain.username: admin
    sensitiveProperties:
      sasl.plain.password: admin
keys:
  # predefined.service: tsp-api
  token: bcd55b3e-c0d1-4374-84f4-b9277674fb46
db:
  host: postgresql
  port: 5432
  name: vrp
  user: vrp
  password: vrp_password
