kafka:
  solver:
    sensitiveProperties:
      sasl.plain.password: '' # TODO
  dm:
    sensitiveProperties:
      sasl.plain.password: '' # TODO
keys:
  # сервисный токен tsp-api
  token: '' # TODO
db:
  password: '' # TODO
