{{- if .Values.segmentDetector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search-api-v8.fullname" . }}-segment-detector
  labels:
    {{- include "search-api-v8.labels" . | nindent 4 }}
    search/part: segment-detector
    {{- if (.Values.dgctlStorage).manifest }}
    {{- with (include "search-api-v8.manifestCode" .) }}
    manifest: {{ . | quote }}
    {{- end }}{{- /* include "search-api-v8.manifestCode" */}}
    {{- end }}{{- /* .Values.dgctlStorage */}}
spec:
  {{- if not .Values.segmentDetector.hpa.enabled }}
  replicas: {{ .Values.segmentDetector.replicaCount }}
  {{- end }}{{- /* not .Values.segmentDetector.hpa.enabled */}}
  selector:
    matchLabels:
      {{- include "search-api-v8.selectorLabels" . | nindent 6 }}
    {{- with .Values.segmentDetector.matchLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}{{- /* .Values.segmentDetector.matchLabels */}}
      search/part: segment-detector
  template:
    metadata:
      annotations:
      {{- with .Values.segmentDetector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.segmentDetector.podAnnotations */}}
        checksum/config: {{ (include (print $.Template.BasePath "/common/configmap.yaml") . | fromYaml).data | toYaml | sha256sum }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ .Values.magg.ports.metrics | quote }}
        prometheus.io/scrape: "true"
      labels:
        {{- include "search-api-v8.labels" . | nindent 8 }}
      {{- with .Values.segmentDetector.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.segmentDetector.podLabels */}}
        search/part: segment-detector
    spec:
      terminationGracePeriodSeconds: 120
      volumes:
        {{- if .Values.segmentDetector.data.persistent.enabled }}
        - name: segment-detector-data
          ephemeral:
            volumeClaimTemplate:
              metadata:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  {{- .Values.segmentDetector.data.resources | toYaml | nindent 18 }}
                storageClassName: {{ .Values.segmentDetector.data.storageClassName | quote }}
                volumeMode: Filesystem
        {{ else }}
        - name: segment-detector-data
          emptyDir:
            sizeLimit: {{ .Values.segmentDetector.data.resources.requests.storage }}
        {{- end }}{{- /* .Values.segmentDetector.data.persistent.enabled */}}
        - name: segment-detector-sentry
          emptyDir:
            sizeLimit: {{ .Values.sentry.storageSize }}
        - name: segment-detector-config
          configMap:
            name: {{ include "search-api-v8.fullname" . }}
            defaultMode: 420
      containers:
        - name: segment-detector
          securityContext:
            {{- toYaml .Values.segmentDetector.securityContext | nindent 12 }}
          image: '{{ required "A valid .Values.dgctlDockerRegistry entry required" .Values.dgctlDockerRegistry }}/{{ .Values.segmentDetector.image.repository }}:{{ .Values.segmentDetector.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.segmentDetector.image.pullPolicy }}
          ports:
            - name: segdetector-srv
              containerPort: {{ .Values.segmentDetector.ports.server }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.segmentDetector.ports.grpc }}
              protocol: TCP
            - name: monitor
              containerPort: {{ .Values.segmentDetector.ports.monitor }}
              protocol: TCP
            - name: http-syncer
              containerPort: {{ .Values.syncer.ports.http }}
              protocol: TCP
          resources:
            {{- toYaml .Values.segmentDetector.resources | nindent 12 }}
          {{- if .Values.customCAs.bundle }}
            {{- include "search-api-v8.custom.ca.volumeMounts" . | nindent 12 }}
          {{- end }}{{- /* .Values.customCAs.bundle */}}
          volumeMounts:
            - name: segment-detector-data
              mountPath: /data
            - name: segment-detector-config
              mountPath: /app/segment_detector_vars.yaml
              subPath: segment_detector_vars.yaml
          {{- if .Values.segmentDetector.livenessProbe.enabled }}
          livenessProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.segmentDetector.livenessProbe "enabled") "context" $) | nindent 12 -}}
          {{ end -}}{{- /* .Values.segmentDetector.livenessProbe.enabled */}}
          {{- if .Values.segmentDetector.readinessProbe.enabled }}
          readinessProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.segmentDetector.readinessProbe "enabled") "context" $) | nindent 12 -}}
          {{ end -}}{{- /* .Values.segmentDetector.readinessProbe.enabled */}}
          {{- if .Values.segmentDetector.startupProbe.enabled }}
          startupProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.segmentDetector.startupProbe "enabled") "context" $) | nindent 12 -}}
          {{ end -}}{{- /* .Values.segmentDetector.startupProbe.enabled */}}
        - name: syncer
          securityContext:
            {{- toYaml .Values.syncer.securityContext | nindent 12 }}
          image: '{{ required "A valid .Values.dgctlDockerRegistry entry required" .Values.dgctlDockerRegistry }}/{{ .Values.syncer.image.repository }}:{{ .Values.syncer.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.syncer.image.pullPolicy }}
          resources:
            {{- toYaml .Values.syncer.resources | nindent 12 }}
          env:
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "search-api-v8.fullname" . }}
                  key: GIN_MODE
            {{- if .Values.customCAs.bundle }}
            {{- include "search-api-v8.env.custom.ca.path" . | nindent 12 }}
            {{- end }}{{- /* .Values.customCAs.bundle */}}
          volumeMounts:
            - name: segment-detector-data
              mountPath: /data
            - name: segment-detector-sentry
              mountPath: {{ .Values.sentry.databasePath }}
            - name: segment-detector-config
              mountPath: /app/config.yaml
              subPath: syncer-segment-detector.yaml
          {{- if .Values.customCAs.bundle }}
            {{- include "search-api-v8.custom.ca.volumeMounts" . | nindent 12 }}
          {{- end }}{{- /* .Values.customCAs.bundle */}}
        {{- if .Values.magg.enabled }}
        - name: magg
          image: '{{ required "A valid .Values.dgctlDockerRegistry entry required" .Values.dgctlDockerRegistry }}/{{ .Values.magg.image.repository }}:{{ .Values.magg.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.magg.image.pullPolicy }}
          env:
            - name: METRICS_AGGREGATOR_PORT
              value: {{ .Values.magg.ports.metrics | quote }}
            - name: METRICS_AGGREGATOR_SOURCES
              value: "http://127.0.0.1:{{ .Values.segmentDetector.ports.monitor }}/metrics,\
                http://127.0.0.1:{{ .Values.syncer.ports.http }}/metrics"
            - name: GOMAXPROCS
              value: "1"
            {{- if .Values.customCAs.bundle }}
            {{- include "search-api-v8.env.custom.ca.path" . | nindent 12 }}
            {{- end }}{{- /* .Values.customCAs.bundle */}}
          {{- if .Values.customCAs.bundle }}
          volumeMounts:
            {{- include "search-api-v8.custom.ca.volumeMounts" . | nindent 12 }}
          {{- end }}{{- /* .Values.customCAs.bundle */}}
          ports:
            - containerPort: {{ .Values.magg.ports.metrics }}
          resources:
            {{- toYaml .Values.magg.resources | nindent 12 }}
        {{ end }}{{- /* .Values.magg.enabled */}}
      serviceAccountName: {{ include "search-api-v8.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.segmentDetector.podSecurityContext | nindent 8 }}
  strategy:
  {{- .Values.segmentDetector.strategy | toYaml | nindent 4 }}
{{ end }}{{- /* .Values.segmentDetector.enabled */}}
