{{- if has .Values.postgres.tls.mode (list "verify-ca" "verify-full") -}}
{{- include "update-manager.psql.checks" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "update-manager.name" . }}-psql-tls
  labels:
    {{- include "update-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
type: Opaque
data:
  {{- if has .Values.postgres.tls.mode (list "verify-ca" "verify-full") }}
  {{- with .Values.postgres.tls.rootCert }}
  psql-server-ca.crt: {{ . | b64enc }}
  {{- end }}
  {{- if eq .Values.postgres.tls.mode "verify-full" }}
  {{- with .Values.postgres.tls.key }}
  psql-client.key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.postgres.tls.cert }}
  psql-client.crt: {{ . | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
