{{- $sslEnabled := include "kafka.ssl.enabled" . }}
{{- $password := .Values.kafka.password }}
{{- if or ($sslEnabled) (not (empty $password)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keys.kafka.name" . | quote }}
  labels:
    {{- include "keys.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $sslEnabled }}
  client.crt: {{ required "A valid kafka.tls.clientCert entry required" .Values.kafka.tls.clientCert | b64enc | quote }}
  client.key: {{ required "A valid kafka.tls.clientKey entry required" .Values.kafka.tls.clientKey | b64enc | quote }}
  ca.crt: {{ required "A valid kafka.tls.serverCA entry required" .Values.kafka.tls.serverCA | b64enc | quote }}
  {{- end }}
  {{- with $password }}
  password: {{ $password | b64enc }}
  {{- end }}
{{- end }}
