{{- if .Values.api.ingress.enabled -}}
{{- include "stat-api.ingress.checks" (dict "global" $ "ingress" .Values.api.ingress "name" "api") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stat-api.componentname" (dict "global" $ "component" "api") }}
  labels:
    {{- include "stat-api.labels" (dict "global" $ "component" "api") | nindent 4 }}
  {{- with include "stat-api.ingress.annotations" (dict "global" $ "ingress" .Values.api.ingress) }}
  annotations:
  {{- . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- with include "stat-api.ingress.tls" (dict "global" $ "ingress" .Values.api.ingress "secretName" (printf "%s-tls" (include "stat-api.componentname" (dict "global" $ "component" "api")))) }}
  tls:
  {{- . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              {{- include "stat-api.ingress.backend" (dict "global" $ "name" (include "stat-api.componentname" (dict "global" $ "component" "api")) "port" $.Values.api.service.port) | nindent 14 }}
          {{- end }}
    {{- end }}
{{- end }}
