{{- define "merger.pdb" }}
metadata:
  name: {{ include "navi-async-matrix.fullname" . }}-merger
{{- end }}
{{ if .Values.dm.merger.pdb.enabled }}
{{- template "generic-chart.merge" (list
    (merge (dict "pdbctx" .Values.dm.merger.pdb) .)
    "merger.pdb"
    "generic-chart.pdb.tpl"
) }}
{{- end }}
