auth:
  password: clickhouse
configdFiles:
  kafka.xml: |
    <yandex>
      <kafka>
        <security_protocol>sasl_plaintext</security_protocol>
        <sasl_mechanism>SCRAM-SHA-512</sasl_mechanism>
        <sasl_username>admin</sasl_username>
        <sasl_password>admin</sasl_password>
      </kafka>
    </yandex>
