apiVersion: v2
name: platform-id
type: application
description: A Helm chart for Kubernetes to deploy Platform-ID

version: 2.11.1
appVersion: 1.5.0

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com

dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
