apiVersion: v1
kind: Secret
metadata:
  name: {{ include "staticmaps.fullname" . }}
  labels:
    {{- include "staticmaps.labels" . | nindent 4 }}

type: Opaque
data:
  tilesKey: {{ required "Valid .Values.tiles.key required!" .Values.tiles.key | b64enc }}
  {{- if .Values.app.access.enabled }}
  accessToken:  {{ required "Valid .Values.keys.token required!" .Values.keys.token | b64enc }}
  {{- end }}
