{{- if .Values.unisearcher.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search-api-v8.fullname" . }}-unisearcher
  labels:
    {{- include "search-api-v8.labels" . | nindent 4 }}
    search/part: unisearcher
    {{- if (.Values.dgctlStorage).manifest }}
    {{- with (include "search-api-v8.manifestCode" .) }}
    manifest: {{ . | quote }}
    {{- end }}{{- /* include "search-api-v8.manifestCode" */}}
    {{- end }}{{- /* .Values.dgctlStorage */}}
spec:
  {{- if not .Values.unisearcher.hpa.enabled }}
  replicas: {{ .Values.unisearcher.replicaCount }}
  {{- end }}{{- /* not .Values.unisearcher.hpa.enabled */}}
  selector:
    matchLabels:
      {{- include "search-api-v8.selectorLabels" . | nindent 6 }}
      search/part: unisearcher
    {{- with .Values.unisearcher.matchLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}{{- /* .Values.unisearcher.matchLabels */}}
  template:
    metadata:
      annotations:
      {{- with .Values.unisearcher.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.unisearcher.podAnnotations */}}
        checksum/config: {{ (include (print $.Template.BasePath "/common/configmap.yaml") . | fromYaml).data | toYaml | sha256sum }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ .Values.magg.ports.metrics | quote }}
        prometheus.io/scrape: "true"
      labels:
        {{- include "search-api-v8.labels" . | nindent 8 }}
        search/part: unisearcher
        role: unisearcher
      {{- with .Values.unisearcher.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.unisearcher.podLabels */}}
    spec:
      terminationGracePeriodSeconds: 120
      {{- with .Values.unisearcher.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.unisearcher.imagePullSecrets */}}
      serviceAccountName: {{ include "search-api-v8.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.unisearcher.podSecurityContext | nindent 8 }}
      containers:
        - name: unisearcher
          securityContext:
            {{- toYaml .Values.unisearcher.securityContext | nindent 12 }}
          image: '{{ required "A valid .Values.dgctlDockerRegistry entry required" .Values.dgctlDockerRegistry }}/{{ .Values.unisearcher.image.repository }}:{{ .Values.unisearcher.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.unisearcher.image.pullPolicy }}
          {{- if .Values.customCAs.bundle }}
          env:
            {{- include "search-api-v8.env.custom.ca.path" . | nindent 12 }}
          {{- end }}{{- /* .Values.customCAs.bundle */}}
          ports:
            - name: http-port
              containerPort: {{ .Values.unisearcher.ports.http }}
              protocol: TCP
            - name: grpc-port
              containerPort: {{ .Values.unisearcher.ports.grpc }}
              protocol: TCP
            - name: http-syncer
              containerPort: {{ .Values.syncer.ports.http }}
              protocol: TCP
            - name: http-metrics
              containerPort: {{ .Values.unisearcher.ports.monitor }}
              protocol: TCP
          {{- if .Values.unisearcher.livenessProbe.enabled }}
          livenessProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.unisearcher.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}{{- /* .Values.unisearcher.livenessProbe.enabled */}}
          {{- if .Values.unisearcher.readinessProbe.enabled }}
          readinessProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.unisearcher.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end -}}{{- /* .Values.unisearcher.readinessProbe.enabled */}}
          {{- if .Values.unisearcher.startupProbe.enabled }}
          startupProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.unisearcher.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- end -}}{{- /* .Values.unisearcher.startupProbe.enabled */}}
          volumeMounts:
            - name: unisearcher-sentry
              mountPath: {{ .Values.sentry.databasePath }}
            - name: unisearcher-data
              mountPath: /data
            - name: unisearcher-config
              mountPath: /app/unisearcher_vars.yaml
              subPath: unisearcher_vars.yaml
          {{- if .Values.customCAs.bundle }}
            {{- include "search-api-v8.custom.ca.volumeMounts" . | nindent 12 }}
          {{- end }}{{- /* .Values.customCAs.bundle */}}
          resources:
            {{- toYaml .Values.unisearcher.resources | nindent 12 }}
        - name: syncer
          securityContext:
            {{- toYaml .Values.syncer.securityContext | nindent 12 }}
          image: '{{ required "A valid .Values.dgctlDockerRegistry entry required" .Values.dgctlDockerRegistry }}/{{ .Values.syncer.image.repository }}:{{ .Values.syncer.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.syncer.image.pullPolicy }}
          resources:
            {{- toYaml .Values.syncer.resources | nindent 12 }}
          env:
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "search-api-v8.fullname" . }}
                  key: GIN_MODE
            {{- if .Values.customCAs.bundle }}
            {{- include "search-api-v8.env.custom.ca.path" . | nindent 12 }}
            {{- end }}{{- /* .Values.customCAs.bundle */}}
          volumeMounts:
            - name: unisearcher-data
              mountPath: /data
            - name: unisearcher-config
              mountPath: /app/config.yaml
              subPath: syncer-worker.yaml
            {{- if .Values.customCAs.bundle }}
              {{- include "search-api-v8.custom.ca.volumeMounts" . | nindent 12 }}
            {{- end }}{{- /* .Values.customCAs.bundle */}}
        {{- if .Values.magg.enabled }}
        - name: magg
          image: '{{ required "A valid .Values.dgctlDockerRegistry entry required" .Values.dgctlDockerRegistry }}/{{ .Values.magg.image.repository }}:{{ .Values.magg.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.magg.image.pullPolicy }}
          env:
            - name: METRICS_AGGREGATOR_PORT
              value: {{ .Values.magg.ports.metrics | quote }}
            - name: METRICS_AGGREGATOR_SOURCES
              value: "http://127.0.0.1:{{ .Values.unisearcher.ports.monitor }}/metrics,\
                      http://127.0.0.1:{{ .Values.syncer.ports.http }}/metrics"
            - name: GOMAXPROCS
              value: "1"
            {{- if .Values.customCAs.bundle }}
            {{- include "search-api-v8.env.custom.ca.path" . | nindent 12 }}
            {{- end }}{{- /* .Values.customCAs.bundle */}}
          {{- if .Values.customCAs.bundle }}
          volumeMounts:
            {{- include "search-api-v8.custom.ca.volumeMounts" . | nindent 12 }}
          {{- end }}{{- /* .Values.customCAs.bundle */}}
          ports:
            - containerPort: {{ .Values.magg.ports.metrics }}
          resources:
            {{- toYaml .Values.magg.resources | nindent 12 }}
        {{ end }}{{- /* .Values.magg.enabled */}}
      volumes:
        {{- if .Values.unisearcher.data.persistent.enabled }}
        - name: unisearcher-data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: {{ .Values.unisearcher.data.storageClassName | quote }}
                volumeMode: Filesystem
                resources:
                  {{- .Values.unisearcher.data.resources | toYaml | nindent 18 }}
        {{ else }}
        - name: unisearcher-data
          emptyDir:
            sizeLimit: {{ .Values.unisearcher.data.resources.requests.storage }}
        {{ end }}{{- /* .Values.unisearcher.data.persistent.enabled */}}
        - name: unisearcher-sentry
          emptyDir:
            sizeLimit: {{ .Values.sentry.storageSize }}
        - name: unisearcher-config
          configMap:
            name: {{ include "search-api-v8.fullname" . }}
      {{- with .Values.unisearcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.unisearcher.nodeSelector */}}
      {{- with .Values.unisearcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.unisearcher.affinity */}}
      {{- with .Values.unisearcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.unisearcher.tolerations */}}
  strategy:
  {{- .Values.unisearcher.strategy | toYaml | nindent 4 }}
{{- end }}{{- /* .Values.unisearcher.enabled */}}
