apiVersion: v2
name: staticmaps
type: application
description: A Helm chart for Kubernetes to deploy StaticMaps service

version: 2.55.0
appVersion: 1.0.2

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
