kafka:
  properties:
    bootstrap.servers: kafka-controller-headless:9092
    security.protocol: SASL_PLAINTEXT
    sasl.mechanism: SCRAM-SHA-512
    sasl.plain.username: admin
  sensitiveProperties:
    sasl.plain.password: admin
db:
  host: postgresql
  port: 5432
  name: async_matrix
  user: async_matrix
  schema: public
  password: async_matrix
keys:
  # predefined.service: distance-matrix-api
  token: 0c70a612-e12a-4d39-b99b-1e1f6a74152d
