{{- if or .Values.api.catalogApiKey .Values.api.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.api.catalogApiKey }}
  webApiKey: {{ .Values.api.catalogApiKey | b64enc }}
  {{- end }}
  {{- if .Values.api.key }}
  key: {{ .Values.api.key | b64enc }}
  {{- end }}
{{- end }}
