apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
type: Opaque
data:
  webApiKey: {{ .Values.api.webApiKey | b64enc }}
  key: {{ .Values.api.key | b64enc }}
