kafka:
  properties:
    bootstrap.servers: kafka-controller-headless:9092
    security.protocol: SASL_PLAINTEXT
    sasl.mechanism: SCRAM-SHA-512
    sasl.plain.username: admin
  sensitiveProperties:
    sasl.plain.password: admin
