kafka:
  properties:
    bootstrap.servers: server # TODO
    security.protocol: SASL_PLAINTEXT # TODO
    sasl.mechanism: SCRAM-SHA-512 # TODO
    sasl.plain.username: test-username # TODO
  sensitiveProperties:
    sasl.plain.password: '' # TODO
