externalDatabase:
  user: keycloak
  host: postgresql
  port: 5432
  database: keycloak
  password: keycloak
auth:
  adminUser: admin
  adminPassword: admin
defaultUser:
  enabled: true
  name: user
  email: user@test.com
  firstName: user
  lastName: user
  password: userpass
