externalDatabase:
  user: keycloak
  host: 'haproxy' # TODO
  port: 5000 # TODO
  database: keycloak
  password: '' # TODO
auth:
  adminUser: admin
  adminPassword: '' # TODO
defaultUser:
  enabled: true
  name: 'user' # TODO
  email: 'user@test.com' # TODO
  firstName: 'userfirstname' # TODO
  lastName: 'userlastname' # TODO
  password: '' # TODO
