apiVersion: v1
kind: Secret
metadata:
  name: {{ include "search-api-v8.fullname" . }}
  labels:
    {{- include "search-api-v8.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.onpremise }}
  s3AccessKey:  {{ required "Valid .Values.dgctlStorage.accessKey required!" .Values.dgctlStorage.accessKey | b64enc }}
  s3SecretKey:  {{ required "Valid .Values.dgctlStorage.secretKey required!" .Values.dgctlStorage.secretKey | b64enc }}
  s3Host:  {{ required "Valid .Values.dgctlStorage.host required!" .Values.dgctlStorage.host | b64enc }}
{{ else }}
  s3AccessKey:  {{ required "Valid .Values.s3.accessKey required!" .Values.s3.accessKey | b64enc }}
  s3SecretKey:  {{ required "Valid .Values.s3.secretKey required!" .Values.s3.secretKey | b64enc }}
  s3Host:  {{ required "Valid .Values.s3.host required!" .Values.s3.host | b64enc }}
  masterApiKey:  {{ required "Valid .Values.ingressRouter.masterApiKey required!" .Values.ingressRouter.masterApiKey | b64enc }}
{{ end }}{{- /* .Values.onpremise */}}
