---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "update-manager.migrate.name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "update-manager.labels" . | nindent 4 }}
data:
  migrate.yaml: |
    db:
      endpoint: {{ required "Valid .Values.postgres.host required!" .Values.postgres.host }}:{{ .Values.postgres.port }}
      db-name: {{ required "Valid .Values.postgres.name required!" .Values.postgres.name }}
      user: {{ required "Valid .Values.postgres.username required!" .Values.postgres.username }}
      params:
        {{- include "update-manager.psql.params" . | nindent 8 }}
