---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "update-manager.migrate.name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "update-manager.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ required "Valid .Values.postgres.password required!" .Values.postgres.password | b64enc }}
