{{- if .Values.api.ingress.enabled -}}
{{- include "keys.ingress.checks" (dict "ctx" $ "ingress" .Values.api.ingress "name" "api") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keys.api.name" . }}
  labels:
    {{- include "keys.api.labels" . | nindent 4 }}
  {{- with include "keys.ingress.annotations" (dict "ctx" $ "ingress" .Values.api.ingress) }}
  annotations:
  {{- . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- with include "keys.ingress.tls" (dict "ctx" $ "ingress" .Values.api.ingress "secretName" (printf "%s-tls" (include "keys.api.name" $))) }}
  tls:
  {{- . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: "/service/v1"
            pathType: Prefix
            backend:
              {{- include "keys.ingress.backend" (dict "ctx" $ "name" (include "keys.serviceAPI.name" $) "port" $.Values.serviceApi.service.port) | nindent 14 }}
          - path: "/public/v1"
            pathType: Prefix
            backend:
              {{- include "keys.ingress.backend" (dict "ctx" $ "name" (include "keys.serviceAPI.name" $) "port" $.Values.serviceApi.service.port) | nindent 14 }}
          - path: "/"
            pathType: Prefix
            backend:
              {{- include "keys.ingress.backend" (dict "ctx" $ "name" (include "keys.api.name" $) "port" $.Values.api.service.port) | nindent 14 }}
    {{- end }}
{{- end }}
