apiVersion: v1
kind: Secret
metadata:
  name: {{ include "citylens.web.name" . }}-secret
  labels:
    {{- include "citylens.web.labels" . | nindent 4 }}
type: Opaque
data:
  cookiesSecretKey: {{ required "Valid .Values.web.cookiesSecretKey required!" .Values.web.cookiesSecretKey | b64enc }}
