api:
  postgres:
    host: postgresql
    port: 5432
    username: catalog
    name: catalog
    poolSize:
      api: 20
    queryTimeout: 10
    password: catalog_password
importer:
  postgres:
    host: postgresql
    port: 5432
    username: catalog
    name: catalog
    password: catalog_password
keys:
  # predefined.service.aliases: catalog_apis
  token: 48a6cd36-7cef-4457-97ab-bc4a009f6521
