api:
  postgres: &postgres
    host: 'haproxy' # TODO
    port: 5000 # TODO
    username: catalog
    name: catalog
    poolSize:
      api: 20
    queryTimeout: 10
    password: '' # TODO
importer:
  postgres:
    <<: *postgres
    password: '' # TODO
keys:
  # сервисный токен catalog_apis
  token: '' # TODO
