{{- define "navi-front.service" }}
metadata:
  labels:
    navigroup: {{ .Values.navigroup | default "" | quote }}
{{- end }}{{- /* define "navi-front.service" */}}
{{- template "generic-chart.merge" (list . "navi-front.service" "generic-chart.service.tpl") }}
