{{- if .Values.pagerenderer.settings.enabled }}
{{- if .Values.pagerenderer.settings.grpcRouteHost }}

apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "pro-api.pagerenderer-name" . }}
  namespace: urbigeo
spec:
  hostnames:
    - {{ .Values.pagerenderer.settings.grpcRouteHost }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: canary
      namespace: istio-gateways
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: stable
      namespace: istio-gateways
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "pro-api.pagerenderer-name" . }}
          port: {{ .Values.pagerenderer.settings.grpcPort }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /

{{- end }}
{{- end }}
